### ISSUE TITLE
How to set the SERVICE_SECRET / PROXEUS_SERVICE_SECRET?

### ISSUE THREAD

**Issue by stefanvogel65** [ProxeusApp/node-mail-sender#1]
There is the parameter to set in the docker-compose.yml for the SERVICE_SECRET that is used, I guess, to authenticate against the Proxeus core app, right?

How do you set this in the Proxeus core app (or wherever else it is required)?

Thanks in advance for your guidance

**Comment by loleg** [comment]
Thanks for your question @stefanvogel65 and apologies for the slow reply. 

The idea is that the parameter is set automatically by Docker, which assigns a random hash value to the variable at build time and propagates it to containers. More information can be found at https://github.com/compose-spec/compose-spec/blob/master/spec.md#secrets-top-level-element

There is therefore no parameter or option to set, and there should not be a need for you to set this manually, unless you are running nodes on different hosts. In which case you should raise an issue with more detail about your use case [at core](https://github.com/ProxeusApp/proxeus-core/issues).

**Comment by stefanvogel65** [comment]
Thank you, @loleg for the clarification.
